#!/bin/bash
# Ce script est execute avant de lancer les cas tests

# Generation des interfaces pour l'etat initial:
# On suppose que gmsh a deja ete execute avec cette commande:
# gmsh bulle3.geo -2

# Generation de 4 bulles a 4 positions differentes:
rm -f deplacements.txt
for k in 0.00161 0.00501
do
  for j in 0.00161 0.00511
  do
    for i in 0.00181 0.00541
    do
	   echo $i $j $k bulle4.msh >>deplacements.txt
    done
  done
done

./cree_multi_bulles.sh deplacements.txt init.lata


# Pour le test de calcul de distance on cree 3 bulles
cat >deplacements2.txt <<EOF
0.002 0.002 0.002 bulle4.msh
0.006 0.002 0.002 bulle4.msh
0.002 0.006 0.006 bulle4.msh
EOF
./cree_multi_bulles.sh deplacements2.txt init2.lata

sed -e "s/nb_pas_dt_max 1800/nb_pas_dt_max 600/" \
	-e "s/delta_p_max_repulsion 60/delta_p_max_repulsion 30/" \
	-e "s/sigma   Champ_Uniforme 1 0.07/sigma   Champ_Uniforme 1 0.01/" \
	repulsion.data > repulsion2.data
