#!/bin/bash
# Ce script est execute avant de lancer les cas tests

echo "le prepare genere un fichier .data pour pre_run"
sed -e "s/ nb_pas_dt_max .*/ nb_pas_dt_max 1/g" \
    -e "s/ timestep .*/ timestep 1e-8/g" \
    -e "s/pre_run.sauv/very_coarse.sauv/g" \
    -e "/projection_initiale/s/#//g" \
    -e "s/ nom_reprise.*/ nom_reprise pre_run.sauv/g" \
    -e "s/ seuil 1e-8 precon/ seuil 1e-3 precon/g" \
    -e "s/ seuil 1e-7 # AMG #/ seuil 1e-2 # AMG #/g" \
    temperature_channel_monop.data > pre_run.data
    
