#!/bin/bash
# Ce script est execute avant de lancer les cas tests

cd Ret1
ln -sf ../post_run . 
sed -e "/nom_sauvegarde/d" \
    -e "/nom_reprise/s/#//g" \
    ijkft_canal_perio_monoph_Ret1.data  > ijkft_canal_perio_monoph_Ret1_repr.data

cd ..
mkdir -p Ret1_RK3
cd Ret1_RK3
ln -sf ../post_run . 
# tar xvzf ../init.tgz
sed -e "s/schema_euler_explicite_IJK/Schema_RK3_IJK/g" \
    ../Ret1/ijkft_canal_perio_monoph_Ret1.data > ijkft_canal_perio_monoph_Ret1_RK3.data

sed -e "/nom_sauvegarde/d"  \
    -e "/nom_reprise/s/#//g" \
    ijkft_canal_perio_monoph_Ret1_RK3.data  > ijkft_canal_perio_monoph_Ret1_RK3_repr.data

cd ../Ret180
ln -sf ../post_run . 
tar xzf ../vitesse_Ret180.tgz
sed -e "/nom_sauvegarde/d"  \
    -e "/nom_reprise/s/#//g" \
    ijkft_canal_perio_monoph_Ret180.data  > ijkft_canal_perio_monoph_Ret180_repr.data


cd ..
mkdir -p Ret180_RK3
cd Ret180_RK3
ln -sf ../post_run . 
# tar xvzf ../init.tgz
tar xzf ../vitesse_Ret180.tgz
sed -e "s/schema_euler_explicite_IJK/Schema_RK3_IJK/g" \
    ../Ret180/ijkft_canal_perio_monoph_Ret180.data > ijkft_canal_perio_monoph_Ret180_RK3.data

sed -e "/nom_sauvegarde/d"  \
    -e "/nom_reprise/s/#//g" \
    ijkft_canal_perio_monoph_Ret180_RK3.data  > ijkft_canal_perio_monoph_Ret180_RK3_repr.data
