#!/bin/bash
lata=`ls test_save_each_dt_jdd1_lata_*.sauv.lata 2>/dev/null`
tar xzf ref.tar.gz || exit -1
erreur=0
[ "$lata" = "" ] && echo "no lata files? error!" && exit -1
for f in $lata 
do
  echo "Compare $f with reference..."
  compare_lata $f  ref/$f
  err=$?
  [ $err != 0 ] && erreur=$err
done
exit $erreur

