#!/bin/bash
# ce script est execute avant de lire les cas tests

mkdir -p FINE
sed -e "s/48/96/g"\
    -e "s/nproc 1 1 1/nproc 1 1 3/g" \
    -e "s/nb_pas_dt_max .*/nb_pas_dt_max 30000/g" \
    -e "1 i\# PARALLEL ONLY 3 #" canal_poiseuille.data > FINE/canal_poiseuille.data
sed -e 's/(NR/0.5*(NR/g' post_run > FINE/post_run


