#!/bin/bash
# Ce script est execute avant de lancer les cas tests

# ./schema_temps.sh
# ./convection.sh
# ./diffusion.sh
#
# Creation d'un cas CONVECTION en z:
sed -e "s/_i /www/" \
    -e "s/_k/_i/" \
    -e "s/www/_k /" \
    -e "s/_vx/www/" \
    -e "s/_vz/_vx/" \
    -e "s/www/_vz/" \
    -e "s/_x/www/" \
    -e "s/_z/_x/" \
    -e "s/www/_z/" \
    -e "s/bctype_i/bctype_k/" \
    -e "s/0.003201 0.01325001 0.01245303125/0.01245303125 0.01325001 0.003201/" \
    -e "s/0.003325 0.016001 0.01245303125/0.01245303125 0.016001 0.003325/" \
   convection.data > convectionz.data

sed -e "s/_i /_k /g" \
    -e "s/CONVECTION/CONVECTIONZ/" \
    -e "s/convection/convectionz/" \
    -e "s/VX/VZ/g" \
    -e "/valx/s/4/8/" \
    -e "/cvgx_L2/s/3/5/" \
    convection.sh > convectionz.sh

chmod +x convectionz.sh
mkdir -p PAR
cp post_run PAR
for fic in "convection" "convectionz" "schema_temps" "diffusion"
do
   # sh ./$fic.sh
   # Il faut penser pour le ghost a avoir assez de mailles par proc 
   # (ie au moins  5)
   sed -e "s/nproc 1 1 1/nproc 2 2 2/g" $fic.data > PAR/${fic}_par8.data
done
