#!/bin/bash
# Ce script est execute avant de lancer les cas tests
[ -f $1.lml ] && gzip -f $1.lml

# python ./ordre_cvg.py
cas=`echo $1`
[ $cas = "temperature_convergence_CLwall" ] && echo "Fin du post-run sans lancer de convergence sur $1" && exit
\rm -fr CONVERGENCE 
mkdir CONVERGENCE
echo "Actually runs the convergence cases into $1/CONVERGENCE"
cd CONVERGENCE/
cp ../$cas.data .
cp ../$cas.sh .
chmod +x ./$cas.sh
./$cas.sh
cd ..
echo "Fin de post traitement"

